stringg : main.o strng.o strng1.o strng2.o 
	gcc -o stringg main.o strng.o strng1.o strng2.o
main.o : main.c
	gcc -c main.c
strng.o : strng.c
	gcc -c strng.c
strng1.o : strng1.c
	gcc -c strng1.c
strng2.o : strng2.c
	gcc -c strng2.c
clean :
	rm main.o strng.o strng1.o strng2.o

